/**
 * 狮城生活圈 · 数据中心 data.js
 * ─────────────────────────────
 * 这是网站唯一数据源，所有餐厅、活动、亲子内容均在此维护。
 * 更新规则：
 *   - 新增条目直接 push 到对应数组
 *   - 已关闭/过期设 active: false（不会显示）
 *   - 演唱会/活动过期后设 active: false
 *   - 每日 sg-living-daily-update 任务负责更新此文件
 *
 * 最后更新：2026-04-11
 * 版本：2.1
 */

const SGLIVING_DATA = {

  meta: {
    lastUpdated: "2026-04-15",
    version: "2.2",
    note: "数据持续累积，active:false 表示已关闭/过期"
  },

  // ════════════════════════════════════════════════
  // 餐厅数据
  // categories: restaurant / dessert / snack / michelin / finedining
  // badge: new / hot / michelin / trending / classic / finedining
  // ════════════════════════════════════════════════
  restaurants: [

    // ── 高端餐厅 Fine Dining ──────────────────────

    {
      id: "yi-jereme-leung",
      name: "艺 yì by Jereme Leung",
      categories: ["restaurant", "michelin", "finedining"],
      rating: 4.9,
      openDate: "2025-09",
      price: "S$120–200",
      description: "莱佛士酒店旗舰中餐厅，主厨梁子庚五周年推出全新单点菜单。招牌「海胆醉熟老虎虾」是当季必点，融合中国各地方菜系精华与现代创意，是新加坡顶级中餐体验首选，高端宴请与纪念日不二之选。",
      tags: ["海胆虎虾", "地方菜创新", "莱佛士"],
      address: "Raffles Hotel, 1 Beach Road",
      badge: "michelin",
      badgeText: "⭐ 米其林",
      emoji: "🏮",
      bgGradient: "linear-gradient(135deg,#2c3e50,#3498db)",
      catLabel: "正餐",
      catDesc: "地方中餐 / 莱佛士酒店",
      ratingDesc: "米其林推荐 · 五周年新菜单",
      active: true
    },

    {
      id: "1887-by-andre",
      name: "1887 by André",
      categories: ["restaurant", "michelin", "finedining"],
      rating: 4.8,
      openDate: "2026-04",
      price: "S$180–350",
      description: "传奇主厨 André Chiang（江振诚）回归莱佛士酒店，以1887年酒店建成年份命名，呈现「当代遗产美食学」。法式哲学融合新加坡历史与文化记忆，菜单随季节和历史叙事变化，是2026年新加坡最受期待的高端餐厅。",
      tags: ["法式料理", "江振诚", "当代美食"],
      address: "Raffles Hotel Singapore, 1 Beach Road",
      badge: "michelin",
      badgeText: "⭐ 米其林级",
      emoji: "🕯️",
      bgGradient: "linear-gradient(135deg,#1a1a2e,#c0a060)",
      catLabel: "正餐",
      catDesc: "法式当代 / 江振诚 · 莱佛士酒店",
      ratingDesc: "2026年新加坡最受期待顶级餐厅",
      active: true
    },

    {
      id: "sophia-st-regis",
      name: "Sophia · The St. Regis",
      categories: ["restaurant", "finedining"],
      rating: 4.6,
      openDate: "2026-04",
      price: "S$80–150",
      description: "圣瑞吉酒店全新意式高端餐厅，主厨 Angelo Sergio 来自普利亚，菜单涵盖意大利11个大区风味。招牌有自制佛卡夏、牛肉 Bresaola 配羊奶酪蜂蜜、章鱼 Polpo Grigliato，以及精选意大利葡萄酒配对，环境优雅适合商务宴请。",
      tags: ["意式料理", "圣瑞吉", "佛卡夏"],
      address: "The St. Regis Singapore, 29 Tanglin Road",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🇮🇹",
      bgGradient: "linear-gradient(135deg,#2ecc71,#1abc9c)",
      catLabel: "正餐",
      catDesc: "意大利精品 / 圣瑞吉酒店",
      ratingDesc: "11大区意大利菜系全覆盖",
      active: true
    },

    {
      id: "wenzhou-mansion",
      name: "温州馆 Wenzhou Mansion",
      categories: ["restaurant", "finedining"],
      rating: 4.6,
      openDate: "2026-02",
      price: "S$50–80",
      description: "新加坡首家也是唯一一家江浙精品餐厅，120道菜代表温州和东海的饮食多样性。镇店之宝「葱油大黄鱼」鱼肉鲜嫩，被誉为「海之金」，地道江浙风味令人惊艳，适合商务宴请和家庭庆典。",
      tags: ["大黄鱼", "江浙菜", "高档宴请"],
      address: "Scotts Square, 6 Scotts Road",
      badge: "new",
      badgeText: "🆕 首家",
      emoji: "🐟",
      bgGradient: "linear-gradient(135deg,#d4edda,#c3e6cb)",
      catLabel: "正餐",
      catDesc: "浙江菜 / 精品江浙菜",
      ratingDesc: "新加坡首家江浙精细料理",
      active: true
    },

    {
      id: "ban-lan",
      name: "伴澜 Ban Lan 闽菜",
      categories: ["restaurant", "finedining"],
      rating: 4.6,
      openDate: "2026-02",
      price: "S$60–100",
      description: "苏州著名闽菜馆「伴澜」首家海外门店，主厨孙晓洋亲自坐镇。精炼闽南菜注重原汁原味，食材严苛讲究，是品味正宗闽南高端料理的绝佳之选，适合重要商务接待。",
      tags: ["闽南菜", "海外首店", "精品料理"],
      address: "Scotts Square, 6 Scotts Road",
      badge: "new",
      badgeText: "🆕 新开",
      emoji: "🍲",
      bgGradient: "linear-gradient(135deg,#ffeaa7,#fdcb6e)",
      catLabel: "正餐",
      catDesc: "福建菜 / 苏州名店",
      ratingDesc: "苏州名厨掌舵首家海外店",
      active: true
    },

    {
      id: "sabor-chijmes",
      name: "Sabòr · Chijmes",
      categories: ["restaurant", "finedining"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$60–120",
      description: "2026年4月开业，位于 Chijmes 庭院内的100座西班牙餐厅。主厨 Javier Vicente Rejas 是伦敦海鲜饭学校联创人，经典 Tapas 和 Paella 系列令人叫绝。玻璃围合餐厅搭配户外露台，氛围浪漫，适合约会、庆典。",
      tags: ["西班牙菜", "Paella海鲜饭", "Tapas"],
      address: "Chijmes, 30 Victoria Street",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🥘",
      bgGradient: "linear-gradient(135deg,#e74c3c,#c0392b)",
      catLabel: "正餐",
      catDesc: "西班牙料理 / Chijmes庭院",
      ratingDesc: "西班牙传统 Tapas & Paella 专家",
      active: true
    },

    {
      id: "seoul-and-so",
      name: "Seoul & So · 国家美术馆",
      categories: ["restaurant", "finedining"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$80–180",
      description: "新加坡国家美术馆5楼全新韩式烤肉高端餐厅，俯瞰 Ng Teng Fong 屋顶花园装置艺术。供应韩国和牛（Hanwoo）、Handon 猪、日本和牛，可单点或选择分享套餐，是艺术与美食的完美融合。",
      tags: ["韩国烤肉", "和牛", "美术馆"],
      address: "National Gallery Singapore, Level 5, 1 St Andrew's Road",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🥩",
      bgGradient: "linear-gradient(135deg,#2d3436,#636e72)",
      catLabel: "正餐",
      catDesc: "韩式烤肉 / 国家美术馆",
      ratingDesc: "艺术与高端韩牛烤肉完美融合",
      active: true
    },

    // ── 正餐 & 火锅 ──────────────────────────────

    {
      id: "xita-lao-tai-tai",
      name: "西塔老太太烤肉",
      categories: ["restaurant"],
      rating: 4.7,
      openDate: "2026-04",
      price: "S$40–60",
      description: "荣获「中国烤肉连锁第一」的品牌正式登陆新加坡！28种特调腌制肉类，炭火砂锅现烤，香气四溢。必点：特制腌制牛舌、秘制猪颈肉、蒜香鱿鱼。适合聚会宴客，烤肉爱好者必打卡！",
      tags: ["炭火烤肉", "腌制肉类", "中国品牌"],
      address: "Bugis+, 201 Victoria St",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍖",
      bgGradient: "linear-gradient(135deg,#ff6b35,#f7c59f)",
      catLabel: "正餐",
      catDesc: "烧烤 / 中国No.1烤肉连锁",
      ratingDesc: "中国烤肉连锁第一品牌",
      active: true
    },

    {
      id: "lead-general-hotpot",
      name: "将军火锅 Lead General Hot Pot",
      categories: ["restaurant"],
      rating: 4.6,
      openDate: "2026-04",
      price: "S$35–55",
      description: "招牌「将军四宫格锅」让你同时品尝四种汤底！必点：将军地狱麻辣牛油锅（$7++）、将军鱼肚鸡汤锅（$11++，25种草药熬制）。适合一家大小同享，口味各异不再争执！",
      tags: ["四宫格火锅", "麻辣鸳鸯", "家庭聚餐"],
      address: "Tiong Bahru Plaza, 302 Tiong Bahru Rd #02-117 | 每天11am–10pm",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🔥",
      bgGradient: "linear-gradient(135deg,#e74c3c,#c0392b)",
      catLabel: "正餐",
      catDesc: "四宫格火锅 / 中国连锁",
      ratingDesc: "四宫格锅底同时享用",
      active: true
    },

    {
      id: "pang-pang",
      name: "彭彭 Pang Pang 锅锅",
      categories: ["restaurant"],
      rating: 4.7,
      openDate: "2026-01",
      price: "S$30–45",
      description: "国内超火大锅菜，首家新加坡店落户 Guoco Midtown。必点签名螃蟹锅（500g 约 S$78），每日新鲜斯里兰卡螃蟹，锅底浓郁鲜甜，非常适合家庭聚餐。国内700+门店品质保证。",
      tags: ["螃蟹锅", "家庭聚餐", "中国口味"],
      address: "Guoco Midtown, 128 Beach Road, Bugis",
      badge: "new",
      badgeText: "🆕 新开",
      emoji: "🦀",
      bgGradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
      catLabel: "正餐",
      catDesc: "砂锅 / 中国连锁",
      ratingDesc: "国内700+门店首进新加坡",
      active: true
    },

    {
      id: "sio-pasta",
      name: "Sio Pasta（东京米其林）",
      categories: ["restaurant", "michelin"],
      rating: 4.7,
      openDate: "2026-04",
      price: "S$15–30",
      description: "东京米其林餐厅 Sio Aoyama 旗下副牌，连续6年登上米其林指南，首家国际门店落地 Raffles City！日式精准工艺融合意大利面食，招牌「明太子意面」（$16.80）配明太子、紫苏、海苔，新鲜手工意面从 $13.80 起，米其林级体验触手可及。",
      tags: ["明太子意面", "日式意大利", "米其林品牌"],
      address: "Raffles City Shopping Centre",
      badge: "michelin",
      badgeText: "⭐ 米其林认可",
      emoji: "🍝",
      bgGradient: "linear-gradient(135deg,#f8d7a0,#f4a261)",
      catLabel: "正餐",
      catDesc: "日式意面 / 米其林6连载",
      ratingDesc: "东京米其林指南6年连续上榜",
      active: true
    },

    {
      id: "tonkatsu-daiki",
      name: "炸猪排 Tonkatsu Daiki（大阪米其林）",
      categories: ["restaurant", "michelin"],
      rating: 4.6,
      openDate: "2026-04",
      price: "S$25–40",
      description: "大阪道顿堀米其林认证炸猪排名店首次进军海外！每块猪排包裹粗粒面包糠，低温慢炸出金黄酥脆外皮，内里鲜嫩多汁。搭配磨碎萝卜柚子酱油、红味噌汁三种酱料，层次丰富，适合全家聚餐。",
      tags: ["炸猪排", "大阪风味", "米其林品牌"],
      address: "Ngee Ann City, 391 Orchard Road",
      badge: "michelin",
      badgeText: "⭐ 大阪米其林",
      emoji: "🥩",
      bgGradient: "linear-gradient(135deg,#f5deb3,#daa520)",
      catLabel: "正餐",
      catDesc: "炸猪排 / 大阪道顿堀风味",
      ratingDesc: "大阪道顿堀米其林名店进驻",
      active: true
    },

    {
      id: "smash-street",
      name: "Smash Street 汉堡",
      categories: ["restaurant"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$14–25",
      description: "Scarpetta 意面团队打造的全新汉堡专门店！经过30+次配方迭代的招牌 Smash Burger，热铁板压薄牛肉饼形成焦脆边缘，内里多汁。搭配双炸薯条和玉米片奶昔，性价比超高的精品汉堡体验，从 $14 起。",
      tags: ["Smash汉堡", "精品牛肉饼", "玉米片奶昔"],
      address: "Amoy Street, Telok Ayer",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍔",
      bgGradient: "linear-gradient(135deg,#d4a017,#8b6914)",
      catLabel: "正餐",
      catDesc: "精品汉堡 / Scarpetta团队",
      ratingDesc: "30次迭代完美牛肉饼配方",
      active: true
    },

    {
      id: "rice-meatmen",
      name: "Rice by The Meatmen",
      categories: ["restaurant"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$15–28",
      description: "新加坡百万粉丝 YouTube 频道 The Meatmen 的首家实体餐厅！亚洲家常美食为主，招牌叻沙海鲜泡饭配椰香浓汤和脆米花，炭油收尾的秘制鱼汤，以及辛辣虾仁糯米卷，平价亲民，充满创意。",
      tags: ["叻沙泡饭", "亚洲家常菜", "网红餐厅"],
      address: "Rasa Space, 多媒体体验馆",
      badge: "new",
      badgeText: "🆕 首家实体",
      emoji: "🍚",
      bgGradient: "linear-gradient(135deg,#e67e22,#d35400)",
      catLabel: "正餐",
      catDesc: "亚洲家常菜 / The Meatmen Group",
      ratingDesc: "百万订阅YouTube频道首家实体店",
      active: true
    },

    {
      id: "golden-chopsticks",
      name: "金筷子 Golden Chopsticks",
      categories: ["restaurant"],
      rating: 4.5,
      openDate: "2025-12",
      price: "S$35–55",
      description: "新加坡首家云贵川概念餐厅，融合云南、贵州、四川三省风味。从麻辣火锅到酸汤鱼、贵州串串，口味层次丰富，嗜辣的朋友不容错过！特别适合爱吃辣的家庭。",
      tags: ["麻辣", "酸汤鱼", "云南菜"],
      address: "Clarke Quay 区域",
      badge: "trending",
      badgeText: "🔥 趋势",
      emoji: "🌶️",
      bgGradient: "linear-gradient(135deg,#fd79a8,#e17055)",
      catLabel: "正餐",
      catDesc: "云贵川 / 新派中餐",
      ratingDesc: "新加坡首家云贵川概念餐厅",
      active: true
    },

    {
      id: "the-soup-expert",
      name: "汤的专家 The Soup Expert",
      categories: ["restaurant"],
      rating: 4.3,
      openDate: "2026-01",
      price: "S$25–40",
      description: "源自上海的炖汤名店，专注老火慢炖煲汤，配合家禽和海鲜料理。每道汤需炖煮数小时，浓缩食材精华，口感醇厚。特别适合注重养生的家庭和追求健康饮食的朋友。",
      tags: ["老火靓汤", "养生", "上海风味"],
      address: "具体地址请查询 HungryGoWhere",
      badge: "new",
      badgeText: "🆕 新开",
      emoji: "🫕",
      bgGradient: "linear-gradient(135deg,#dfe6e9,#b2bec3)",
      catLabel: "正餐",
      catDesc: "老火靓汤 / 上海名店",
      ratingDesc: "上海名店进驻新加坡",
      active: true
    },

    {
      id: "nai-nai-flavor",
      name: "椿花奶奶 Nai Nai Flavor 杭帮菜",
      categories: ["restaurant"],
      rating: 4.7,
      openDate: "2026-04",
      price: "S$35–55",
      description: "杭州人气江浙菜品牌「椿花奶奶」首家海外店落户 i12 Katong！正宗杭帮菜讲究「轻口重味」，招牌砂锅鸡汤鲜甜不腻，精致江南点心让人舍不得放筷子。在新加坡吃到杭州味道，简直不要太幸福！",
      tags: ["杭帮菜", "江浙风味", "海外首店"],
      address: "i12 Katong, 112 East Coast Road",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🏮",
      bgGradient: "linear-gradient(135deg,#fd79a8,#e84393)",
      catLabel: "正餐",
      catDesc: "杭州江浙菜 / 海外首店",
      ratingDesc: "杭州人气品牌首次出海",
      active: true
    },

    {
      id: "linkus-fujian",
      name: "Linkus 福建菜",
      categories: ["restaurant"],
      rating: 4.5,
      openDate: "2026-03",
      price: "S$25–45",
      description: "以正宗福建（闽菜）料理为主打，扎根 Suntec City。招牌海鲜焖面、卤肉饭、福建炒虾面地道正宗，注重食材新鲜度和原汁原味。闽南家乡菜情结浓厚，很多福建华人专程来吃。",
      tags: ["福建菜", "海鲜焖面", "闽南风味"],
      address: "Suntec City Mall",
      badge: "new",
      badgeText: "🆕 新开",
      emoji: "🦞",
      bgGradient: "linear-gradient(135deg,#0652dd,#1289a7)",
      catLabel: "正餐",
      catDesc: "福建菜 / 闽南海鲜",
      ratingDesc: "地道正宗闽南风味",
      active: true
    },

    {
      id: "shisen-hanten",
      name: "四川饭店 Shisen Hanten（2星米其林）",
      categories: ["restaurant", "michelin", "finedining"],
      rating: 4.9,
      openDate: "2024-01",
      price: "S$80–150",
      description: "由陈建一之子陈建太郎主理的新加坡2星米其林川菜，坐落于希尔顿乌节酒店。将日本极致料理精神融入麻辣四川菜，麻婆豆腐、担担面等经典川菜在这里升华成艺术品。想体验顶级川菜，这里是最佳选择。",
      tags: ["米其林2星", "高端川菜", "陈建太郎"],
      address: "Hilton Singapore Orchard, 333 Orchard Road",
      badge: "michelin",
      badgeText: "⭐⭐ 2星米其林",
      emoji: "🌶️",
      bgGradient: "linear-gradient(135deg,#c0392b,#8e1d0e)",
      catLabel: "正餐",
      catDesc: "四川菜 / 日本米其林监制",
      ratingDesc: "2颗米其林星 · 顶级川菜殿堂",
      active: true
    },

    {
      id: "xiabu-xiabu",
      name: "小霸王 Xiabu Xiabu 火锅茶饮",
      categories: ["restaurant", "dessert"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$25–40",
      description: "国内超过1000家门店的连锁火锅品牌首次登陆新加坡！一人食小锅概念，自选汤底+精选食材，搭配旗下 Tea Mi Tea 的芋泥珍珠奶茶。吃完热气腾腾的火锅来杯冰凉奶茶，绝配！一个人也能吃得很爽！",
      tags: ["一人食火锅", "奶茶搭配", "中国连锁"],
      address: "Bras Basah 区域",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍲",
      bgGradient: "linear-gradient(135deg,#e17055,#fdcb6e)",
      catLabel: "正餐",
      catDesc: "一人食火锅 / 奶茶组合",
      ratingDesc: "国内1000+门店首进新加坡",
      active: true
    },

    {
      id: "sushidan-hiroyuki",
      name: "寿司段 Sushidan by Chef Hiroyuki Sato",
      categories: ["restaurant", "michelin"],
      rating: 4.6,
      openDate: "2026-01",
      price: "S$12–30",
      description: "日本著名料理人佐藤宏幸在莱佛士城推出的亲民回转寿司！江户前寿司工艺遇上亲民价格，寿司从 S$1.99 起、刺身 S$2.99 起、套餐 S$19.90 起。米其林级师傅级品质却是美食广场价格，性价比极高，是寿司爱好者的周中福音！",
      tags: ["江户前寿司", "刺身", "亲民价格"],
      address: "Raffles City Shopping Centre",
      badge: "michelin",
      badgeText: "⭐ 米其林师傅",
      emoji: "🍣",
      bgGradient: "linear-gradient(135deg,#e8f4f8,#2980b9)",
      catLabel: "正餐",
      catDesc: "江户前寿司 / 日本米其林师傅",
      ratingDesc: "米其林大厨操刀 · 寿司从$1.99起",
      active: true
    },

    // ── 甜品饮料 ──────────────────────────────────

    {
      id: "molly-tea",
      name: "茉莉奶白 Molly Tea",
      categories: ["dessert"],
      rating: 4.8,
      openDate: "2026-03",
      price: "S$6–10",
      description: "国内超热门奶茶品牌，2026年3月正式登陆新加坡乌节路！茉莉花奶茶清香不甜腻，芝士奶盖系列更是一绝，排队人气超高。即将在 Raffles Place 开设第二家分店。全球2000+门店品质保证。",
      tags: ["茉莉奶茶", "芝士奶盖", "中国品牌"],
      address: "Orchard Central, 181 Orchard Rd（6月 Raffles Place 新店开业）",
      badge: "hot",
      badgeText: "🔥 大热",
      emoji: "🧋",
      bgGradient: "linear-gradient(135deg,#e0c3fc,#8ec5fc)",
      catLabel: "甜品饮料",
      catDesc: "奶茶 / 中国网红品牌",
      ratingDesc: "全球2000+门店",
      active: true
    },

    {
      id: "more-yogurt",
      name: "More Yogurt 莓优格",
      categories: ["dessert"],
      rating: 4.4,
      openDate: "2025-10",
      price: "S$8–15",
      description: "中国酸奶连锁巨头登陆新加坡，所有产品采用天然发酵酸奶和新鲜水果制作，杜绝糖浆和添加剂。浓郁奶香配新鲜草莓、芒果等时令水果，清爽健康，孩子也超爱！",
      tags: ["天然酸奶", "鲜果", "健康"],
      address: "Suntec City, 3 Temasek Blvd",
      badge: "trending",
      badgeText: "🆕 中国品牌",
      emoji: "🍓",
      bgGradient: "linear-gradient(135deg,#a8edea,#fed6e3)",
      catLabel: "甜品饮料",
      catDesc: "酸奶 / 鲜果饮品",
      ratingDesc: "中国酸奶饮品巨头",
      active: true
    },

    {
      id: "ah-chew-desserts",
      name: "阿秋甜品 Ah Chew Desserts",
      categories: ["dessert"],
      rating: 4.6,
      openDate: "2005-01",
      price: "S$4–8",
      description: "新加坡最知名港式甜品店之一，60+甜品种类，超级平价！强烈推荐：榴莲西米露、杨枝甘露、芋头西米露、鲜奶炖蛋。牛车水门口常年排队，绝对是甜品爱好者的天堂。",
      tags: ["杨枝甘露", "炖蛋", "港式甜品"],
      address: "1 Liang Seah St #01-10/11",
      badge: "hot",
      badgeText: "💯 老字号",
      emoji: "🥭",
      bgGradient: "linear-gradient(135deg,#f6d365,#fda085)",
      catLabel: "甜品饮料",
      catDesc: "港式甜品 / 老字号",
      ratingDesc: "60种甜品 · 本地必打卡",
      active: true
    },

    {
      id: "cafe-mary-grace",
      name: "Café Mary Grace（菲律宾国宝）",
      categories: ["dessert"],
      rating: 4.4,
      openDate: "2026-04",
      price: "S$8–18",
      description: "来自菲律宾的国宝级甜品咖啡馆，首次走出菲律宾落地新加坡丹戎巴葛！招牌 Ensaymada 面包松软香甜，Cheese Rolls 奶香浓郁。新加坡限定：咸蛋黄 Ensaymada 和班兰椰酱芝士卷，是甜品控的新宝藏。",
      tags: ["Ensaymada", "芝士卷", "菲律宾甜品"],
      address: "Tras Street, Tanjong Pagar",
      badge: "new",
      badgeText: "🆕 海外首店",
      emoji: "🥐",
      bgGradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
      catLabel: "甜品饮料",
      catDesc: "菲律宾甜品咖啡 / 海外首店",
      ratingDesc: "菲律宾国宝甜品品牌首家海外店",
      active: true
    },

    {
      id: "park-side-cafe",
      name: "Park Side Café · 植物园",
      categories: ["dessert"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$18–35",
      description: "PS.Cafe 团队在新加坡植物园全新推出的全日制咖啡馆，早午餐从早8点供应至下午4点。菜单融合罗望子、芒果、叻沙等本地元素，招牌蜂鸟薄饼（$22）配焦糖菠萝和椰子乳酪，在植物园绿意中用餐别有韵味。",
      tags: ["全日早午餐", "植物园", "PS.Cafe"],
      address: "Singapore Botanic Gardens",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🌿",
      bgGradient: "linear-gradient(135deg,#a8e6cf,#3d9970)",
      catLabel: "甜品饮料",
      catDesc: "全日咖啡馆 / 新加坡植物园",
      ratingDesc: "PS.Cafe全新植物园旗舰概念店",
      active: true
    },

    // ── 小吃快食 ──────────────────────────────────

    {
      id: "numb-sichuan",
      name: "Numb 四川风味",
      categories: ["snack"],
      rating: 4.5,
      openDate: "2025-11",
      price: "S$20–35",
      description: "主打四川特色美食，招牌菜「叫花土豆」和「糖醋手撕包菜」大受好评，冒烤鸭因独特风味曾一度断货。性价比超高，是中国留学生和华人最爱打卡的馆子之一。",
      tags: ["叫花土豆", "冒烤鸭", "四川菜"],
      address: "City Hall / Chinatown 区域",
      badge: "hot",
      badgeText: "🔥 排队",
      emoji: "🫙",
      bgGradient: "linear-gradient(135deg,#ff7675,#d63031)",
      catLabel: "小吃快食",
      catDesc: "四川菜 / 网红小馆",
      ratingDesc: "冒烤鸭一度断货",
      active: true
    },

    {
      id: "xiao-noodles",
      name: "小面 Xiao Noodles",
      categories: ["snack"],
      rating: 4.4,
      openDate: "2026-01",
      price: "S$12–18",
      description: "专注重庆麻辣小面，必点「红碗牛肉面」，麻辣鲜香、劲道爽口。适合工作日午餐快食，价格亲民，让你在新加坡也能吃到地道重庆味道。",
      tags: ["重庆小面", "麻辣", "平价"],
      address: "Somerset, 313@somerset 附近",
      badge: "new",
      badgeText: "🆕 新开",
      emoji: "🍜",
      bgGradient: "linear-gradient(135deg,#e17055,#d63031)",
      catLabel: "小吃快食",
      catDesc: "重庆小面 / 中国品牌",
      ratingDesc: "重庆麻辣风味",
      active: true
    },

    {
      id: "song-fa-bkt",
      name: "松发肉骨茶",
      categories: ["snack"],
      rating: 4.7,
      openDate: "1969-01",
      price: "S$12–18",
      description: "新加坡最具代表性的肉骨茶名店，猪骨汤底加入中药炖煮数小时，香气浓郁，肉质软烂。是每位华人来新必打卡的美食，适合早午餐享用，配油条更是一绝！",
      tags: ["猪骨汤", "中药卤料", "早午餐"],
      address: "New Bridge Rd / Balestier 等多个分店",
      badge: "hot",
      badgeText: "💯 必吃",
      emoji: "🍖",
      bgGradient: "linear-gradient(135deg,#8b5e3c,#c8956c)",
      catLabel: "小吃快食",
      catDesc: "肉骨茶 / 新加坡国民美食",
      ratingDesc: "来新加坡必吃",
      active: true
    },

    {
      id: "chick-fil-a",
      name: "Chick-fil-A 亚洲首家",
      categories: ["snack"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$12–20",
      description: "美国最受欢迎炸鸡连锁品牌全亚洲第一家开在新加坡 Bugis+！招牌经典炸鸡三明治外皮酥脆、鸡肉多汁，配 Waffle 薯条和特制酱汁，在美国常年排长队。亚洲首次登陆！",
      tags: ["炸鸡三明治", "美式快餐", "亚洲首店"],
      address: "Bugis+, 201 Victoria St（已开业！）",
      badge: "new",
      badgeText: "🆕 亚洲首店",
      emoji: "🍗",
      bgGradient: "linear-gradient(135deg,#dc143c,#b22222)",
      catLabel: "小吃快食",
      catDesc: "美式炸鸡 / 全球最大连锁之一",
      ratingDesc: "美国最受欢迎炸鸡连锁",
      active: true
    },

    {
      id: "karii-okinawa",
      name: "Karii 冲绳街头美食",
      categories: ["snack"],
      rating: 4.4,
      openDate: "2026-04",
      price: "S$3–10",
      description: "来自冲绳的街头美食小店登陆 Suntec City！招牌萨塔安达吉（冲绳炸甜甜圈，$2.50）外酥内软香甜，现点现炸；冲绳荞麦面（$8.80起）汤底清甜，猪骨加柴鱼熬制数小时。加上冲绳风格饭团，价格超亲民，逛商场时的完美轻食选择！",
      tags: ["冲绳甜甜圈", "荞麦面", "街头小吃"],
      address: "Suntec City, 3 Temasek Boulevard",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍡",
      bgGradient: "linear-gradient(135deg,#f8c471,#e67e22)",
      catLabel: "小吃快食",
      catDesc: "冲绳街头美食 / 日本风味",
      ratingDesc: "冲绳正宗风味轻食",
      active: true
    },

    {
      id: "burnt-cones-downtown",
      name: "Burnt Cones Downtown · 24小时咖啡馆",
      categories: ["dessert"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$7–12",
      description: "新加坡第一家24小时营业的明胶咖啡馆（Gelato Coffee）！深夜馋甜品再也不用忍了。招牌自制蛋筒香脆可口，黑芝麻明胶、班兰椰子口味一绝；搭配现磨咖啡，是深夜续命的绝佳组合。IOI Central Boulevard 位置方便，CBD 上班族最新打卡地！",
      tags: ["明胶咖啡", "24小时", "自制蛋筒"],
      address: "2 Central Boulevard, IOI Central Boulevard Towers",
      badge: "new",
      badgeText: "🆕 24H营业",
      emoji: "🍦",
      bgGradient: "linear-gradient(135deg,#2c3e50,#bdc3c7)",
      catLabel: "甜品饮料",
      catDesc: "明胶咖啡 / 24小时营业",
      ratingDesc: "新加坡首家24小时明胶咖啡馆",
      active: true
    },

    {
      id: "longjing-restaurant",
      name: "LONGJING 绿茶餐厅",
      categories: ["restaurant"],
      rating: 4.7,
      openDate: "2025-08",
      price: "S$5.80–30",
      description: "来自杭州西湖边的国民级浙菜品牌终于落户新加坡！招牌东坡肉慢炖软糯入味，龙井烤鸡茶香四溢，宋嫂鱼羹鲜甜如梦。白墙黛瓦的江南风装修让人恍若置身杭城，适合想念家乡味的朋友聚餐首选！平价实惠，人均不到$30。",
      tags: ["东坡肉", "浙江菜", "江南风格"],
      address: "Suntec City Mall #01-384, 3 Temasek Boulevard, Singapore 038983",
      badge: "hot",
      badgeText: "📕 小红书爆款",
      emoji: "🍃",
      bgGradient: "linear-gradient(135deg,#2d9a60,#55efc4)",
      catLabel: "正餐",
      catDesc: "浙江菜 / 新达城购物中心",
      ratingDesc: "杭州人气国民品牌 · 东坡肉必点",
      active: true
    },

    {
      id: "modu-high",
      name: "MODU High 韩式参鸡汤",
      categories: ["restaurant"],
      rating: 4.6,
      openDate: "2026-04",
      price: "S$38–74",
      description: "姐妹们！新加坡终于有高端参鸡汤了绝绝子！MODU High 在安祥山小巷里藏着，12种草药汤底随意选，从经典人参到黑松露口味任君挑剔。锅里还泡着整只鸡，戳开皮肉汁水四溢，配上糯米饭超满足。四月新开，已经排队爆了！",
      tags: ["参鸡汤", "韩式料理", "4月新开"],
      address: "Amoy Street, Tanjong Pagar, Singapore",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍲",
      bgGradient: "linear-gradient(135deg,#e17055,#fdcb6e)",
      catLabel: "正餐",
      catDesc: "韩式参鸡汤 / 安祥山",
      ratingDesc: "12种草药汤底 · 松露参鸡汤限定",
      active: true
    },

    {
      id: "niku-niku-oh-kome",
      name: "Niku Niku Oh Kome",
      categories: ["restaurant"],
      rating: 4.5,
      openDate: "2026-04",
      price: "S$16.80",
      description: "来自日本的汉堡牛排专门店，热石锅桌边烤制超有仪式感！点餐后服务员端来烧得通红的石板，经典和牛版本咬下去肉汁暴涌，配上蓬松白米饭和温泉蛋，简直是打工人的治愈午餐。$16.80 一份性价比超高，朋友推荐必去！",
      tags: ["汉堡牛排", "日式", "热石烤制"],
      address: "Westgate, 3 Gateway Drive, #B2, Jurong East",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🥩",
      bgGradient: "linear-gradient(135deg,#2d3436,#e17055)",
      catLabel: "正餐",
      catDesc: "日式汉堡牛排 / 裕廊东 Westgate",
      ratingDesc: "热石桌边烤制 · 和牛系列必点",
      active: true
    },

    {
      id: "yaowarat-cafe",
      name: "Yaowarat Café 泰式早餐",
      categories: ["snack"],
      rating: 4.4,
      openDate: "2026-04",
      price: "S$8–15",
      description: "4月8日新开，全天供应泰式铁板蛋（Kai Krata）！联创人有泰国血统确保正宗。招牌 Yaowarat Kai Krata（$7.80）含泰式罗勒碎肉、培根和特调蛋比，本地融合款有泰式绿茶咖椰吐司（$2）和娘惹铁板蛋（$9.80）。",
      tags: ["泰式铁板蛋", "全天早午餐", "本地融合"],
      address: "CBD 中心商务区",
      badge: "new",
      badgeText: "🆕 4月新开",
      emoji: "🍳",
      bgGradient: "linear-gradient(135deg,#f39c12,#e67e22)",
      catLabel: "小吃快食",
      catDesc: "泰式早餐 / 全天供应",
      ratingDesc: "正宗泰式铁板蛋全天供应",
      active: true
    }
  ],

  // ════════════════════════════════════════════════
  // 活动数据
  // type: concert / exhibition / event
  // priority: featured（华人/世界顶流，排最前）/ normal
  // active: false 表示已过期
  // ════════════════════════════════════════════════
  events: [

    // ── ⭐ 重点推荐：华人演唱会 & 世界顶流 ─────────

    {
      id: "gem-gloria-tour",
      name: "邓紫棋 G.E.M. · I AM GLORIA 世界巡演 2.0",
      type: "concert",
      priority: "featured",
      featuredReason: "华语天后连演6晚",
      month: "MAY",
      day: "26",
      dow: "周二",
      dateColor: "linear-gradient(135deg,#e8533a,#c0392b)",
      typeLabel: "🎤 华语天后",
      typeColor: "#e8533a",
      description: "华语乐坛天后邓紫棋全新世界巡演 2.0 新加坡站！演绎《光年之外》《倒数》《句号》《新的心跳》等经典热曲，震撼现场演出。连演6晚（5月26–31日），华语乐迷绝对不可错过！",
      venue: "Singapore Indoor Stadium",
      dateRange: "5月26–31日，连演6晚",
      ticketInfo: "🎫 Ticketmaster / KLOOK",
      price: "S$108–388",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=GEM+Gloria+Singapore",
      btnText: "购票",
      sortDate: "2026-05-26",
      active: true
    },

    {
      id: "eric-chou-universe",
      name: "周興哲 Eric Chou · Universe 世界巡演",
      type: "concert",
      priority: "featured",
      featuredReason: "台湾情歌天王两天连演",
      month: "APR",
      day: "11",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#2d3436,#636e72)",
      typeLabel: "🎤 华语情歌",
      typeColor: "#2d3436",
      description: "台湾情歌天王周興哲最新世界巡演新加坡站！以宇宙星际为主题，沉浸式舞台体验，演绎《怎么了》《你，好不好》《以後別做朋友》等心碎情歌。两天连演，华语乐迷必到！",
      venue: "Singapore Indoor Stadium",
      dateRange: "4月11–12日，两天连演",
      ticketInfo: "🎫 Ticketmaster",
      price: "S$108–288",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg",
      btnText: "购票",
      sortDate: "2026-04-11",
      active: false
    },

    {
      id: "laufey-matter-of-time",
      name: "Laufey · A Matter of Time 亚洲巡演",
      type: "concert",
      priority: "featured",
      featuredReason: "格莱美奖得主",
      month: "MAY",
      day: "19",
      dow: "周二",
      dateColor: "linear-gradient(135deg,#0984e3,#74b9ff)",
      typeLabel: "🎸 格莱美得主",
      typeColor: "#0984e3",
      description: "格莱美奖得主冰岛创作歌手 Laufey 亚洲巡演新加坡站！演绎新专辑《Goddess》《Promise》等温柔爵士流行曲目，深受全球乐迷追捧。票已售罄，关注候补票平台。",
      venue: "Singapore Indoor Stadium",
      dateRange: "5月19日",
      ticketInfo: "⚠️ 票已售罄",
      price: "S$88–198",
      priceNote: "已售罄",
      ticketUrl: "https://www.ticketmaster.sg/search?q=Laufey+Singapore",
      btnText: "候补票",
      sortDate: "2026-05-19",
      active: true
    },

    {
      id: "rainie-yang",
      name: "楊丞琳 Rainie Yang 新加坡演唱会",
      type: "concert",
      priority: "featured",
      featuredReason: "台湾知名歌手",
      month: "APR",
      day: "26",
      dow: "周日",
      dateColor: "linear-gradient(135deg,#fd79a8,#e84393)",
      typeLabel: "🎤 华语流行",
      typeColor: "#e84393",
      description: "台湾知名创作歌手楊丞琳新加坡演唱会，演绎《雨爱》《暧昧》《带我走》等经典情歌，以及全新专辑曲目，多媒体舞台视觉效果惊艳，深受华语乐迷喜爱。",
      venue: "The Star Theatre",
      dateRange: "4月26日",
      ticketInfo: "🎫 SISTIC",
      price: "S$88–218",
      priceNote: "SISTIC",
      ticketUrl: "https://www.sistic.com.sg/events/search?q=Rainie+Yang",
      btnText: "购票",
      sortDate: "2026-04-26",
      active: true
    },

    // ── 普通活动 ──────────────────────────────────

    {
      id: "artbox-camp-2026",
      name: "ARTBOX CAMP 2026",
      type: "event",
      priority: "normal",
      month: "APR",
      day: "10",
      dow: "周五",
      dateColor: "linear-gradient(135deg,#e8533a,#ff6b4a)",
      typeLabel: "🎪 市集嘉年华",
      typeColor: "#e8533a",
      description: "新加坡最大创意市集全新升级！250+独立品牌、现场演出、儿童工作坊、ARTBOX Arcade 和复古游乐场。第二周末（4月17–20日）即将到来，错过第一波的朋友赶紧安排！门票仅 S$5 起。",
      venue: "Singapore Expo, Hall 3",
      dateRange: "4月17–20日（第二周末）12pm–11pm",
      ticketInfo: "⏰ 12pm–11pm",
      price: "S$5+",
      priceNote: "部分活动免费",
      ticketUrl: "https://www.artboxsingapore.com",
      btnText: "了解详情",
      sortDate: "2026-04-17",
      active: true
    },

    {
      id: "sakura-gbtb",
      name: "花穹樱花展 · 石川縣特别版（已结束）",
      type: "exhibition",
      priority: "normal",
      month: "APR",
      day: "15",
      dow: "周三",
      dateColor: "linear-gradient(135deg,#fd79a8,#e84393)",
      typeLabel: "🌸 主题展览",
      typeColor: "#e84393",
      description: "Gardens by the Bay 花穹馆内盛放真实樱花树！重现日本石川县武士和艺伎街区，还有三丽鸥角色特别亮相。已于4月15日结束。",
      venue: "Gardens by the Bay · Flower Dome",
      dateRange: "已结束（截至4月15日）",
      ticketInfo: "👨‍👩‍👧 亲子适合",
      price: "S$12–20",
      priceNote: "随票入园",
      ticketUrl: "https://www.gardensbythebay.com.sg/en/things-to-do/calendar-of-events.html",
      btnText: "购票",
      sortDate: "2026-04-15",
      active: false
    },

    {
      id: "tulipmania-2026",
      name: "花穹郁金香展 · Tulipmania 2026",
      type: "exhibition",
      priority: "normal",
      month: "APR",
      day: "24",
      dow: "周五",
      dateColor: "linear-gradient(135deg,#fd79a8,#e84393)",
      typeLabel: "🌷 花卉展览",
      typeColor: "#e84393",
      description: "Gardens by the Bay 年度花穹盛事回归！超过20万株荷兰进口郁金香铺满整个花穹，色彩缤纷、香气馥郁。今年特设荷兰风车打卡区，亲子家庭必来的春季限定体验，持续至5月17日。",
      venue: "Gardens by the Bay · Flower Dome",
      dateRange: "4月24日–5月17日",
      ticketInfo: "👨‍👩‍👧 亲子必去",
      price: "S$12起",
      priceNote: "含花穹门票",
      ticketUrl: "https://www.gardensbythebay.com.sg/en/things-to-do/calendar-of-events/tulipmania.html",
      btnText: "购票",
      sortDate: "2026-04-24",
      active: true
    },

    {
      id: "day6-decade",
      name: "DAY6 10周年纪念演唱会",
      type: "concert",
      priority: "normal",
      month: "APR",
      day: "18",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#fdcb6e,#e17055)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#e17055",
      description: "韩国创作乐团 DAY6 出道10周年新加坡首次体育馆级别演出！演绎2025年专辑《The DECADE》及经典曲目，现场乐器全 live 演奏，是真正的音乐盛宴！",
      venue: "Singapore Indoor Stadium",
      dateRange: "4月18日",
      ticketInfo: "🎫 Ticketmaster",
      price: "S$108–268",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=DAY6+Singapore+2026",
      btnText: "购票",
      sortDate: "2026-04-18",
      active: true
    },

    {
      id: "demon-slayer-exhibition",
      name: "鬼灭之刃 全集中展览 · 东南亚独家",
      type: "exhibition",
      priority: "normal",
      month: "APR",
      day: "19",
      dow: "周日",
      dateColor: "linear-gradient(135deg,#2d3436,#e17055)",
      typeLabel: "⚔️ 动漫展览",
      typeColor: "#2d3436",
      description: "《鬼灭之刃》东南亚唯一一站！21,000平方尺超大展区，等比例实景重现、多感官互动体验，带你穿越到大正时代。二次元迷和亲子家庭都超适合！",
      venue: "前新加坡体育馆图书馆",
      dateRange: "4月起开放（持续数月）",
      ticketInfo: "🎌 东南亚独家站",
      price: "S$28–48",
      priceNote: "现场购票",
      ticketUrl: "https://www.ticketmaster.sg/search?q=Demon+Slayer+Singapore",
      btnText: "购票",
      sortDate: "2026-04-19",
      active: true
    },

    {
      id: "bfg-musical",
      name: "Roald Dahl's The BFG 亲子音乐剧",
      type: "exhibition",
      priority: "normal",
      month: "APR",
      day: "22",
      dow: "周三",
      dateColor: "linear-gradient(135deg,#a29bfe,#6c5ce7)",
      typeLabel: "🎭 亲子音乐剧",
      typeColor: "#6c5ce7",
      description: "改编自罗尔德·达尔经典绘本《好心眼儿巨人》的英语音乐剧！精彩舞台呈现、魔法般的舞美效果，非常适合带孩子一起欣赏，激发小朋友想象力。",
      venue: "Esplanade Theatre",
      dateRange: "4月22日–5月9日",
      ticketInfo: "👧 适合6岁+",
      price: "S$35–95",
      priceNote: "SISTIC",
      ticketUrl: "https://www.sistic.com.sg/events/search?q=BFG+Singapore",
      btnText: "购票",
      sortDate: "2026-04-22",
      active: true
    },

    {
      id: "bellygom-carnival",
      name: "Bellygom 粉色熊嘉年华",
      type: "event",
      priority: "normal",
      month: "APR",
      day: "30",
      dow: "周四",
      dateColor: "linear-gradient(135deg,#fd79a8,#fdcb6e)",
      typeLabel: "🐻 主题嘉年华",
      typeColor: "#fd79a8",
      description: "韩国超人气粉色熊 Bellygom 主题嘉年华在樟宜机场！7米高充气 Bellygom、游戏摊位、互动打卡区和可爱周边，免费入场，非常适合带孩子一起打卡！",
      venue: "Changi Airport",
      dateRange: "持续至5月初",
      ticketInfo: "🎁 免费入场",
      price: "免费",
      priceNote: "部分游戏收费",
      ticketUrl: "https://www.changiairport.com",
      btnText: "了解详情",
      sortDate: "2026-04-30",
      active: true
    },

    {
      id: "ive-world-tour",
      name: "IVE 2nd World Tour · Show What I Am",
      type: "concert",
      priority: "normal",
      month: "MAY",
      day: "09",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#00b894,#00cec9)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#00b894",
      description: "韩国女团 IVE 第二次世界巡演，带来《I AM》《LOVE DIVE》《After LIKE》等热门曲目，加上扩充曲单和成员 Solo 演出，完全不能错过的巡演！",
      venue: "Singapore Indoor Stadium",
      dateRange: "5月9日",
      ticketInfo: "⏰ 6:00 PM",
      price: "S$98–258",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=IVE+World+Tour+Singapore",
      btnText: "购票",
      sortDate: "2026-05-09",
      active: true
    },

    {
      id: "botero-singapore",
      name: "博特罗大师作品展 · 滨海湾花园",
      type: "exhibition",
      priority: "normal",
      month: "MAY",
      day: "15",
      dow: "周五",
      dateColor: "linear-gradient(135deg,#00b894,#00cec9)",
      typeLabel: "🎨 艺术展览",
      typeColor: "#00b894",
      description: "哥伦比亚大师 Fernando Botero 近130件原作在滨海湾花园展出！以圆润夸张的人体雕塑著称，户外雕塑花园完全免费开放，是亲子艺术教育的绝佳机会，持续至5月15日。",
      venue: "Gardens by the Bay",
      dateRange: "持续至5月15日",
      ticketInfo: "🆓 户外区域免费",
      price: "免费",
      priceNote: "户外区域",
      ticketUrl: "https://www.gardensbythebay.com.sg",
      btnText: "了解详情",
      sortDate: "2026-05-15",
      active: true
    },

    {
      id: "treasure-concert",
      name: "TREASURE 新加坡演唱会",
      type: "concert",
      priority: "normal",
      month: "MAY",
      day: "16",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#6c5ce7,#a29bfe)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#6c5ce7",
      description: "韩国男团 TREASURE 新加坡演唱会，演绎最新专辑及经典曲目，升级的舞台制作、视觉效果和音乐编排，绝对是震撼现场！票务4月13日开售。",
      venue: "Singapore Indoor Stadium",
      dateRange: "5月16日",
      ticketInfo: "🎫 4月13日开票",
      price: "S$98–258",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=TREASURE+Singapore+2026",
      btnText: "购票",
      sortDate: "2026-05-16",
      active: true
    },

    {
      id: "dopamine-land",
      name: "Dopamine Land 多巴胺乐园",
      type: "exhibition",
      priority: "normal",
      month: "MAY",
      day: "15",
      dow: "周五",
      dateColor: "linear-gradient(135deg,#fd79a8,#6c5ce7)",
      typeLabel: "🌈 沉浸式展览",
      typeColor: "#6c5ce7",
      description: "风靡伦敦、马德里、迪拜7座城市的全球爆款沉浸式展览！多巴胺色彩和互动装置激发感官体验，Instagram必打卡，持续至5月15日。适合约会、朋友聚会和家庭出游。",
      venue: "新加坡（具体地址查官网）",
      dateRange: "持续至5月15日",
      ticketInfo: "🌟 全球热门展览",
      price: "S$28–48",
      priceNote: "官网购票",
      ticketUrl: "https://www.dopamineland.com",
      btnText: "购票",
      sortDate: "2026-05-15",
      active: true
    },

    {
      id: "555-mart-nene",
      name: "555 Mart · 插画师 Nene 首次海外个展",
      type: "exhibition",
      priority: "normal",
      month: "MAY",
      day: "17",
      dow: "周日",
      dateColor: "linear-gradient(135deg,#fdcb6e,#e17055)",
      typeLabel: "🎨 个人展览",
      typeColor: "#e17055",
      description: "曼谷插画师 Nene 首次海外个展，以便利店为主题，圆珠笔和手工油墨版画风格，充满趣味与温度。限量版画和周边可购入，是文创爱好者的必访展览。",
      venue: "Heartware Store & Gallery, Joo Chiat",
      dateRange: "持续至5月17日",
      ticketInfo: "🖼 限量版画可购",
      price: "免费入场",
      priceNote: "周边另计",
      ticketUrl: "https://www.instagram.com/heartware.sg",
      btnText: "了解详情",
      sortDate: "2026-05-17",
      active: true
    },

    {
      id: "gile-syncopation",
      name: "(G)I-DLE · Syncopation 世界巡演",
      type: "concert",
      priority: "normal",
      month: "JUN",
      day: "13",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#d63031,#e17055)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#d63031",
      description: "韩国女团 (G)I-DLE 全新世界巡演新加坡站，带来全新演唱会概念「Syncopation」，舞台视觉效果和编排全面升级，粉丝绝不可错过！",
      venue: "Singapore Indoor Stadium",
      dateRange: "6月13日",
      ticketInfo: "⏰ 5:00 PM",
      price: "S$98–268",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=G+I-DLE+Singapore+2026",
      btnText: "购票",
      sortDate: "2026-06-13",
      active: true
    },

    {
      id: "chen-arcadia-tour",
      name: "CHEN · Arcadia 亚洲巡演",
      type: "concert",
      priority: "normal",
      month: "APR",
      day: "12",
      dow: "周日",
      dateColor: "linear-gradient(135deg,#2d3436,#636e72)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#2d3436",
      description: "EXO 成员 CHEN 首次个人世界巡演「Arcadia」新加坡站，今明两天最后机会！以温柔高音和深情演绎著称，粉丝期待已久的 Solo 世界巡演，明天（4月12日）演出，请抓紧！",
      venue: "Singapore Indoor Stadium",
      dateRange: "4月12日",
      ticketInfo: "🎫 Ticketmaster",
      price: "S$98–268",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg",
      btnText: "购票",
      sortDate: "2026-04-12",
      active: false
    },

    {
      id: "palm-tree-festival",
      name: "Palm Tree Music Festival 2026",
      type: "event",
      priority: "normal",
      month: "APR",
      day: "18",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#00b894,#00cec9)",
      typeLabel: "🎵 电音节",
      typeColor: "#00b894",
      description: "滨海湾花园草坪盛大电音节！John Summit、Alesso、Layton Giordani、Marlo 四大顶级 DJ 联手演出，在草坪上感受震撼低音和迷幻灯光。新加坡最受期待的户外音乐节之一！",
      venue: "The Meadow, Gardens by the Bay",
      dateRange: "4月18日",
      ticketInfo: "🎡 户外草坪盛宴",
      price: "S$108–188",
      priceNote: "官网购票",
      ticketUrl: "https://www.palmtreemusicfestival.com",
      btnText: "购票",
      sortDate: "2026-04-18",
      active: true
    },

    {
      id: "smart-home-tech-show",
      name: "Smart Home Tech Show 2026",
      type: "exhibition",
      priority: "normal",
      month: "APR",
      day: "30",
      dow: "周四",
      dateColor: "linear-gradient(135deg,#0984e3,#6c5ce7)",
      typeLabel: "🏠 科技展览",
      typeColor: "#0984e3",
      description: "新加坡最大智能家居科技展览！VR 体验、AI 家居控制、智能安防、节能设备齐聚一堂，还有现场演示和专家讲座。免费入场，是了解未来家居趋势的好机会，适合全家一起来！",
      venue: "Suntec Convention Centre",
      dateRange: "4月30日–5月3日",
      ticketInfo: "🆓 免费入场",
      price: "免费",
      priceNote: "免费入场",
      ticketUrl: "https://www.suntecsingapore.com",
      btnText: "免费入场",
      sortDate: "2026-04-30",
      active: true
    },

    {
      id: "sifa-2026",
      name: "新加坡国际艺术节 SIFA 2026",
      type: "event",
      priority: "normal",
      month: "MAY",
      day: "15",
      dow: "周五",
      dateColor: "linear-gradient(135deg,#8e44ad,#9b59b6)",
      typeLabel: "🎭 艺术节",
      typeColor: "#8e44ad",
      description: "新加坡年度最大综合表演艺术盛事，汇集来自全球的戏剧、舞蹈、音乐和多媒体跨界作品！今年特设 Empress Lawn Festival Village 户外嘉年华，部分演出免费开放。华人家庭感受国际艺术氛围、拓展文化视野的绝佳机会，部分亲子节目适合7-9岁小朋友。",
      venue: "多场地 · Empress Lawn & Esplanade",
      dateRange: "5月15日–30日",
      ticketInfo: "🌟 部分演出免费",
      price: "S$20–120",
      priceNote: "部分免费",
      ticketUrl: "https://www.sifa.sg/",
      btnText: "了解详情",
      sortDate: "2026-05-15",
      active: true
    },

    {
      id: "nmixx-zero-frontier",
      name: "NMIXX 1st World Tour · Zero Frontier",
      type: "concert",
      priority: "normal",
      month: "JUN",
      day: "20",
      dow: "周六",
      dateColor: "linear-gradient(135deg,#fdcb6e,#e17055)",
      typeLabel: "🎤 K-POP 演唱会",
      typeColor: "#e17055",
      description: "NMIXX 首次世界巡演新加坡站！带来全新专辑《Episode 1: Zero Frontier》，实验性舞台风格结合超强现场演唱实力，是 K-POP 粉丝的必看演出！",
      venue: "Singapore Indoor Stadium",
      dateRange: "6月20日",
      ticketInfo: "🌟 首次世界巡演",
      price: "S$98–248",
      priceNote: "Ticketmaster",
      ticketUrl: "https://www.ticketmaster.sg/search?q=NMIXX+Singapore+2026",
      btnText: "购票",
      sortDate: "2026-06-20",
      active: true
    }
  ],

  // ════════════════════════════════════════════════
  // 亲子活动
  // ageRange: 适合年龄描述
  // active: false 表示已过期
  // ════════════════════════════════════════════════
  familyActivities: [

    {
      id: "ranger-buddies-2026",
      name: "Ranger Buddies 任务五：探索蜜蜂世界",
      icon: "🐝",
      topGradient: "linear-gradient(90deg,#f59e0b,#fbbf24)",
      ageRange: "最适合 6–10 岁",
      description: "Ranger Buddies 全新第五季任务！孩子与吉祥物小兔 Rudy 一起出发，用 AR 应用完成户外挑战，在互动站点学习蜜蜂生态和气候变化知识。边玩手机 AR 边完成真实任务，是7-9岁孩子最爱的探索模式！全岛多个地点可参与。",
      highlight: "AR 科技结合自然教育，自由探索无需预约，户外运动+知识学习一举两得！7-9岁孩子可独立完成全部任务挑战",
      location: "全岛多个公园及户外场所",
      dateRange: "3月12日–5月31日（每天开放）",
      cost: "免费下载 App 即可参与",
      duration: "约1.5–3小时",
      active: true
    },

    {
      id: "robofest-2026",
      name: "RoboFest 机器人科技节",
      icon: "🤖",
      topGradient: "linear-gradient(90deg,#00b894,#55efc4)",
      ageRange: "最适合 7–12 岁",
      description: "新加坡科学馆首届机器人节，孩子可亲手触摸、操控真实机器人，欣赏机器狗喜剧秀，学习编程入门。互动性超强，是让孩子爱上 STEM 的绝佳机会！",
      highlight: "强互动性 + 激发科技兴趣，7–9岁孩子可独立完成基础编程挑战！",
      location: "Science Centre Singapore",
      dateRange: "已结束（4月9–12日）",
      cost: "S$4+随票入场",
      duration: "约2–3小时",
      active: false
    },

    {
      id: "artbox-kids",
      name: "ARTBOX 儿童创意工作坊",
      icon: "🎨",
      topGradient: "linear-gradient(90deg,#e8533a,#ff6b4a)",
      ageRange: "适合 5–12 岁",
      description: "ARTBOX CAMP 2026 内设专属儿童创意工作坊，让孩子跟着艺术家学习手工制作。同时可逛250+创意摊位、玩复古游乐场，全家一起嗨！",
      highlight: "培养创造力，亲子共同动手制作，全家活动一站搞定",
      location: "Singapore Expo, Hall 3",
      dateRange: "4月10–12日 & 17–20日（两个周末）",
      cost: "S$5–15",
      duration: "半天或全天",
      active: true
    },

    {
      id: "ocean-kids-expert",
      name: "小海洋专家系列 · 新加坡海洋馆",
      icon: "🦈",
      topGradient: "linear-gradient(90deg,#0984e3,#74b9ff)",
      ageRange: "专为 7–12 岁设计",
      description: "新加坡海洋馆「小海洋专家」系列，45分钟专家见面会，孩子可见识潜水员和海洋兽医的工作，还能穿上迷你制服扮演海洋专家！每周末限额开放，需提前预约。",
      highlight: "专为7-12岁设计，近距离接触海洋生物，开拓自然科学视野",
      location: "Singapore Oceanarium",
      dateRange: "每周末（需提前预约）",
      cost: "S$20–30/人",
      duration: "45分钟",
      active: true
    },

    {
      id: "capy-celebration",
      name: "河川生态园 · 水豚宝宝100天庆典",
      icon: "🦫",
      topGradient: "linear-gradient(90deg,#55efc4,#00b894)",
      ageRange: "适合 5–12 岁",
      description: "River Wonders 庆祝水豚宝宝出生100天！专属寻宝路线、主题打卡点、动物丰容活动和管理员讲解。认识世界最大啮齿动物，了解亚马逊雨林生态，超萌超有趣！",
      highlight: "独特生态教育体验，见证限定100天庆典，7-9岁孩子超感兴趣",
      location: "River Wonders, Mandai",
      dateRange: "4月至5月3日",
      cost: "S$37–48/人",
      duration: "2–3小时",
      active: true
    },

    {
      id: "bfg-musical-family",
      name: "BFG 好心眼儿巨人音乐剧",
      icon: "🎭",
      topGradient: "linear-gradient(90deg,#a29bfe,#6c5ce7)",
      ageRange: "适合 6–10 岁",
      description: "罗尔德·达尔经典儿童名著改编成舞台音乐剧，在滨海艺术中心上演。精彩舞台视觉、生动故事讲述，是培养孩子艺术欣赏力、拓展中英文阅读兴趣的好机会。",
      highlight: "英文语境沉浸，适合培养孩子艺术审美，看完可以读原著互动",
      location: "Esplanade Theatre",
      dateRange: "4月22日–5月9日",
      cost: "S$35–95",
      duration: "约90分钟",
      active: true
    },

    {
      id: "minion-land-uss",
      name: "小黄人乐园 · 环球影城",
      icon: "💛",
      topGradient: "linear-gradient(90deg,#fdcb6e,#ffeaa7)",
      ageRange: "适合 5–12 岁",
      description: "环球影城新加坡全新「小黄人乐园」！包含 Buggie Boogie 旋转木马、Silly Swirly 旋转杯等专为小朋友打造的游乐设施，可爱的小黄人角色随时出现合影，孩子保证开心！",
      highlight: "全新开放游乐区，小黄人 IP 深受7-9岁孩子喜爱，亲子欢乐满分",
      location: "Universal Studios Singapore, Sentosa",
      dateRange: "每天开放",
      cost: "S$83–98/人",
      duration: "全天",
      active: true
    },

    {
      id: "my-little-pony-gbtb",
      name: "小马宝莉 · 友谊花瓣展 · 滨海湾花园",
      icon: "🌺",
      topGradient: "linear-gradient(90deg,#fd79a8,#fdcb6e)",
      ageRange: "适合 5–10 岁",
      description: "My Little Pony 来到 Floral Fantasy！彩虹飞翼、碧琪小马、暮光闪闪等角色以中国传统色彩花卉造型重现，超梦幻的花海打卡区，是女孩们最爱的亲子活动！",
      highlight: "IP超受女孩欢迎，花卉主题视觉效果极佳，打卡拍照一流",
      location: "Gardens by the Bay · Floral Fantasy",
      dateRange: "至5月31日",
      cost: "S$10–16/人",
      duration: "约1–2小时",
      active: true
    },

    {
      id: "lego-sentosa",
      name: "LEGO 搭建梦想赛车 · 圣淘沙",
      icon: "🧱",
      topGradient: "linear-gradient(90deg,#e8533a,#fdcb6e)",
      ageRange: "适合 6–10 岁",
      description: "LEGO Build Your Dream Ride 全新体验！孩子搭好的 LEGO 赛车可以直接上「跑道」测试速度，还有换轮计时站挑战和收集徽章活动。完成全部挑战可领取独家 LEGO 小人仔奖励（数量有限）！",
      highlight: "动手创造+实战测试，LEGO 是7-9岁男孩最爱，赛车主题超燃！",
      location: "HyperDrive, Sentosa",
      dateRange: "限时活动进行中",
      cost: "随票入场",
      duration: "约1.5小时",
      active: true
    },

    {
      id: "sam-free-art",
      name: "新加坡美术馆 免费儿童艺术工作坊",
      icon: "🎨",
      topGradient: "linear-gradient(90deg,#a29bfe,#fd79a8)",
      ageRange: "适合 6–12 岁",
      description: "新加坡美术馆（SAM）全新学习馆以「童年」为主题，设有免费纸摄像机制作工坊、导览参观和趣味贴纸活动。培养孩子艺术感受力，免费入场零负担！",
      highlight: "完全免费！寓教于乐，动手创作，是雨天室内亲子活动首选",
      location: "SAM · Tanjong Pagar Distripark",
      dateRange: "至6月28日",
      cost: "🆓 免费",
      duration: "约1–2小时",
      active: true
    },

    {
      id: "tanglin-kids-fun",
      name: "Tanglin Mall 儿童欢乐时光（周末免费）",
      icon: "🎪",
      topGradient: "linear-gradient(90deg,#f59e0b,#fbbf24)",
      ageRange: "适合 5–10 岁",
      description: "每个周末 Tanglin Mall 都为小朋友准备精彩表演！有棉花糖和爆米花免费赠送，还有魔术表演、木偶剧和泡泡秀等现场演出轮番登场。4月11日至5月31日期间每周末举行，完全免费，购物顺便带娃玩！",
      highlight: "完全免费！购物顺便带娃参与，每周不同节目，孩子百看不厌",
      location: "Tanglin Mall, Orchard Road",
      dateRange: "每周末至5月31日",
      cost: "🆓 完全免费",
      duration: "约1小时",
      active: true
    },

    {
      id: "gardens-children-garden",
      name: "Gardens by the Bay · 儿童花园 & 超级树灯光秀",
      icon: "🌿",
      topGradient: "linear-gradient(90deg,#2d9a60,#55efc4)",
      ageRange: "适合 3–12 岁",
      description: "儿童花园提供免费水上游乐区、树屋和探险径，是孩子的户外天堂。入夜后晚7:45和8:45两场「花园狂想曲」灯光秀，音乐与超级树灯光同步，铺上野餐垫免费观赏，是性价比最高的新加坡亲子体验！",
      highlight: "儿童花园免费入场，灯光秀无需购票，全年开放，堪称新加坡最佳免费家庭活动",
      location: "Gardens by the Bay, Marina Bay",
      dateRange: "每天开放 / 灯光秀 7:45 & 8:45pm",
      cost: "儿童花园免费 / 温室另计",
      duration: "2–4小时",
      active: true
    },

    {
      id: "maritime-week-2026",
      name: "新加坡海洋周 · 亲子探索",
      icon: "⚓",
      topGradient: "linear-gradient(90deg,#0652dd,#1289a7)",
      ageRange: "适合 7–12 岁",
      description: "新加坡海洋周专属家庭日！孩子们可以登上真实船只参观、体验航海模拟器、聆听船长讲述新加坡作为世界级港口的故事。让孩子了解新加坡的立国之本，是难得的历史教育体验。",
      highlight: "近距离接触真实船只，激发7-9岁孩子对工程和航海的兴趣，了解新加坡历史，是课外教育的绝佳机会",
      location: "新加坡各海事场所",
      dateRange: "4月25–26日",
      cost: "部分活动免费",
      duration: "2–4小时",
      active: true
    },

    {
      id: "tulipmania-family",
      name: "郁金香展 · 花穹亲子打卡",
      icon: "🌷",
      topGradient: "linear-gradient(90deg,#fd79a8,#fdcb6e)",
      ageRange: "适合 3–12 岁",
      description: "4月24日起，花穹盛开超过20万株荷兰郁金香！彩虹色花海视觉震撼，荷兰风车、迷你种植区让孩子学习植物知识。傍晚光线金黄，是全家最美拍照时刻。花穹室内恒温舒适，晴雨皆宜。",
      highlight: "室内恒温不怕天热，视觉冲击极强，让7-9岁孩子学习植物生长知识，边玩边认识不同品种郁金香",
      location: "Gardens by the Bay · Flower Dome",
      dateRange: "4月24日–5月17日",
      cost: "S$12起/人",
      duration: "约1–2小时",
      active: true
    },

    {
      id: "kayaking-kids",
      name: "亲子皮划艇 · 适合7岁+",
      icon: "🚣",
      topGradient: "linear-gradient(90deg,#0984e3,#00b894)",
      ageRange: "适合 7 岁以上",
      description: "7岁及以上的孩子可以参加亲子皮划艇活动！在新加坡水域享受阳光运动，增强亲子感情。多个租赁地点可选，包括 Kallang River、Punggol 等，周末热门需提前预约。",
      highlight: "7岁恰好可参与，运动+户外+亲子感情三合一，新加坡水上运动最佳入门选择",
      location: "Kallang / Punggol 皮划艇中心",
      dateRange: "每周开放（建议提前预约）",
      cost: "S$15–30/人",
      duration: "约2小时",
      active: true
    }
  ]
};
